### ISSUE TITLE
Unity with DX11 texture can't be registered in CUDA

### ISSUE THREAD

**Issue by davidAlgis** [davidAlgis/InteropUnityCUDA#2]
When I try to register  in CUDA  a texture DX11 that has been created in Unity, I get the following error : `ErrorCuda error: 1 invalid argument`.

**Comment by davidAlgis** [comment]
The texture that has been created in Unity with DX11 API, will have the type `DXGI_FORMAT_R32G32B32A32_TYPELESS` in native plugin. Therefore, they can't be used like that to be registered in CUDA with [`cudaGraphicsD3D11RegisterResource`](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__D3D11.html), because it doesn't accept this format.

**Comment by davidAlgis** [comment]
I use this code to see that :
```c
    ID3D11Texture2D *d3dtex = (ID3D11Texture2D *)_textureHandle;
    assert(d3dtex);
    D3D11_TEXTURE2D_DESC texDesc;
    d3dtex->GetDesc(&texDesc);

    DXGI_FORMAT format = texDesc.Format;
    Log::log().debugLog(std::to_string(format));
```

**Comment by davidAlgis** [comment]
This issue was already reported here : [see issue tracker](https://issuetracker.unity3d.com/issues/cuda-graphics-interop-fails-in-the-native-plugin-when-using-rendertexture)

**Comment by davidAlgis** [comment]
To solve this issue I have to create another texture and copy the content of the texture created in Unity into it. This will cause an overhead...

**Comment by deibich** [comment]
Hello @davidAlgis,

we also plan to use Unity with Cuda and got some code working. During my research I stumbled over your project which looks very promising.

Because we focus on windows + directx I started to implement d3d11.
https://github.com/deibich/InteropUnityCUDA/commits/d3d11

As you can see I used Texture2D and Texture2DArray instead of RenderTexture to get rid of the problem with format ..._TYPLESS.



> To solve this issue I have to create another texture and copy the content of the texture created in Unity into it. This will cause an overhead...

Does the "action_sample_texture_array" work with this workaround?

**Comment by davidAlgis** [comment]
Hi @deibich,
Nice to see that my work is being useful to someone. 
Thanks for the tips to change `RenderTexture` to `Texture2D`, after I saw the [issue tracker](https://issuetracker.unity3d.com/issues/cuda-graphics-interop-fails-in-the-native-plugin-when-using-rendertexture), I had completely given up to make it work without a copy. 
This morning I push [a first version](https://github.com/davidAlgis/InteropUnityCUDA/commit/96ae471066bb8048bfacbaede841e9510a121eb2) that work for texture 2D **with** this copy, but as I except it cause a big overhead.  Thanks to you, I push [another version](https://github.com/davidAlgis/InteropUnityCUDA/commit/428ad9b4d469817594e50f226bcff4b34d45b8d8) that work for texture 2D **without** a copy and the performances are better ! Now I will tackle the problem of the texture 2D array. 

> > To solve this issue I have to create another texture and copy the content of the texture created in Unity into it. This will cause an overhead...

> Does the "action_sample_texture_array" work with this workaround?

On OpenGL, I could registered directly the texture array into a cuda surface object, that was then written with `surf3DWrite`. Therefore, no copy was needed. I hope to find a similar solution for dx11. Do not hesitate if you have any questions.

**Comment by davidAlgis** [comment]
One drawback of using `Texture2D` instead of `RenderTexture` is that a `Texture2D` cannot be written in a compute shader. You get the following error if you try : 
```
Attempting to bind texture as UAV but the texture wasn't created with the UAV usage flag set!
```

I think I will let the 2 options (with and without copy), just in case.
